### ISSUE TITLE
Hausaufgaben eintragen

### ISSUE THREAD

**Issue by ottojo** [ottojo/hausaufgaben#2]

**Comment by ottojo** [comment]
Kannst du das machen? schicke dir gleich SQL dump

**Comment by spekas** [comment]
Was machen? seh nur dein Kommentar

**Comment by ottojo** [comment]
ja ich mache eben die DB, dann pushe ich das mit dem dump

**Comment by spekas** [comment]
ok perfekt

**Comment by ottojo** [comment]
ist hochgeladen

**Comment by spekas** [comment]
bin auch den anderen code nochmal ganz durch, hab alles verstanden

**Comment by ottojo** [comment]
nice! hab die Homework DB noch mal geändert

**Comment by spekas** [comment]
Habs gesehen ist nochma besser!

Aber in der homework db, was is bId?

**Comment by ottojo** [comment]
bookId, nacher noch eine DB für Bücher (für Zusammenarbeit)

**Comment by spekas** [comment]
ah ok, ja richtig hab ich nicht dran gedacht das es das ist

**Comment by spekas** [comment]
soll man mehrere Aufgaben eintragen können oder jeweils nur eine pro hId? und soll man jeder hId noch nen Namen geben können? Das man z.B. bei ner Suche eifnacher Suchen kann.

**Comment by ottojo** [comment]
nein eine ID für jede HA
